name: FB Message Bot

on:
  workflow_dispatch:  # Manually chalaane ke liye
  # schedule:
  #   - cron: '*/15 * * * *'  # Optional: auto run every 15 min

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        run: python hannu.py
